name: Test Deploy Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test-deploy-standard:
    runs-on: ubuntu-latest
    name: Test deploy.sh in standard environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Test deploy.sh script
        run: ./deploy.sh

  test-deploy-cloudshell:
    runs-on: ubuntu-latest
    name: Test deploy.sh in CloudShell environment
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
      env:
        AWS_EXECUTION_ENV: CloudShell

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yum install -y sudo python3-pip
          pip3 install aws-sam-cli

      - name: Test deploy.sh script
        run: ./deploy.sh
